image: ubuntu
# Choose your stack in here. Postgres or mongo or mysql I dont care
stack: node 12, mongodb, redis
# Your env vars to pass apveyor
environment:
  PORT: 3000
  YOURANOTHERSECRET: ill8ha5AtykpCCne9Q0RTDaco57Jww06FGrFkjeK4hw=
install:
  # install modules
  - yarn
# Post-install test scripts.
test_script:
  # run tests
  - yarn mocha
# Don't actually build.
build: off